Update check-logs.yml

diff --git a/.github/workflows/check-logs.yml b/.github/workflows/check-logs.yml
--- a/.github/workflows/check-logs.yml
+++ b/.github/workflows/check-logs.yml
@@ -27,7 +27,7 @@ jobs:
         run: |
           git fetch origin ${{ github.event.pull_request.base.ref }}
           changes=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }} ${{ github.event.pull_request.head.sha }})
-          check_logs=false
+          check=false
           # Print all file names
           echo "Changed files:"
           echo "$changes" | while read -r file; do
@@ -35,13 +35,14 @@ jobs:
             # Check for console.log in the file
             if grep -w "console.log" $file; then
               echo "Found console.log in $file"
-              check_logs=true
+              check=true
+              if [[ "$check" = true ]]; then
+                echo "Error: Console.log found. Failing the run."
+                exit 1
+              fi
             fi
           done
 
           # If console.log is found, fail the run
-          if [[ "$check_logs" = true ]]; then
-            echo "Error: Console.log found. Failing the run."
-            exit 1
-          fi
+         
           echo "$check_logs"
